print("Enter the first complex number: ")
real_part1 = float(input("Enter the real part: "))
imaginary_part1 = float(input("Enter the imaginary part: "))
complex_number1 = complex(real_part1, imaginary_part1)
print("Enter the second complex number: ")
real_part2 = float(input("Enter the real part: "))
imaginary_part2 = float(input("Enter the imaginary part: "))
complex_number2 = complex(real_part2, imaginary_part2)
print(complex_number1+complex_number2)